[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
copy = "FvguztquHUu69aLqk1VnbC9W49jEtc9VUdoQg1bAAj6v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/m1pro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["crates/programs/copy"]
